package com.mule.bpm.poc

import org.mule.MessageExchangePattern;
import com.mule.bpm.poc.Order;
import function com.mule.bpm.poc.Helper.log;

global org.mule.module.bpm.MessageService mule;

# default dialect for the semantic code will be MVEL
dialect "mvel"
 
declare Order
    @role( event )
end 

rule "Select warehouse A"
    lock-on-active
when
    $order : Order( weight > 50 )    
then
	log(drools,"Select warehouse A")
    modify( $order ) { setDestination("WAREHOUSE_A") }
end

rule "Select warehouse B"
    lock-on-active
when
    $order : Order( weight <= 50 )    
then
	log(drools,"Select warehouse B")
    modify( $order ) { setDestination("WAREHOUSE_B") }
end

